# Generated by Django 4.1.3 on 2022-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_receiver_alter_transaction_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FAMILY", "Family"),
                    ("BUSINESS", "Business"),
                    ("FOOD & DRINKS", "Food & Drinks"),
                ],
                max_length=55,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATED", "Created"),
                    ("COMPLETED", "Completed"),
                    ("SCHEDULED", "Scheduled"),
                    ("REQUESTED", "Requested"),
                ],
                default="Created",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                max_length=55,
                null=True,
            ),
        ),
    ]
