# Generated by Django 4.1.3 on 2022-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
