# Generated by Django 4.1.3 on 2022-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_transaction_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
