# Generated by Django 4.1.3 on 2022-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_service_customer_id_service_name_and_more"),
        ("transactions", "0008_alter_transaction_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_transactions",
                to="wallets.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_transactions",
                to="wallets.wallet",
            ),
        ),
    ]
