# Generated by Django 4.1.3 on 2022-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_alter_transaction_receiver_alter_transaction_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="receiver",
            new_name="receiver_wallet",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="sender",
            new_name="sender_wallet",
        ),
    ]
