# Generated by Django 4.1.3 on 2022-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="account_number",
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="pin",
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
